//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.05.24 at 09:54:08 PM ECT 
//


package com.ec.virtualcoin.buy.payment.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="AccountAuth" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Transaction"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="IPAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="DOB" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="SSN" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                   &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="PostCode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="CardNumber" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                   &lt;element name="CardExpMonth" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="CardExpYear" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                   &lt;element name="CardCVV" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *                   &lt;element name="ShipTo"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="PostCode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                             &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="field1" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountID",
    "accountAuth",
    "transaction"
})
@XmlRootElement(name = "Request")
public class Request {

    @XmlElement(name = "AccountID")
    protected int accountID;
    @XmlElement(name = "AccountAuth", required = true)
    protected String accountAuth;
    @XmlElement(name = "Transaction", required = true)
    protected Request.Transaction transaction;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the accountID property.
     * 
     */
    public int getAccountID() {
        return accountID;
    }

    /**
     * Sets the value of the accountID property.
     * 
     */
    public void setAccountID(int value) {
        this.accountID = value;
    }

    /**
     * Gets the value of the accountAuth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountAuth() {
        return accountAuth;
    }

    /**
     * Sets the value of the accountAuth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountAuth(String value) {
        this.accountAuth = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link Request.Transaction }
     *     
     */
    public Request.Transaction getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request.Transaction }
     *     
     */
    public void setTransaction(Request.Transaction value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="IPAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="DOB" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="SSN" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="PostCode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="CardNumber" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *         &lt;element name="CardExpMonth" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
     *         &lt;element name="CardExpYear" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *         &lt;element name="CardCVV" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
     *         &lt;element name="ShipTo"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="PostCode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="field1" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reference",
        "amount",
        "currency",
        "email",
        "ipAddress",
        "phone",
        "firstName",
        "lastName",
        "dob",
        "ssn",
        "address",
        "city",
        "state",
        "postCode",
        "country",
        "cardNumber",
        "cardExpMonth",
        "cardExpYear",
        "cardCVV",
        "shipTo",
        "field1"
    })
    public static class Transaction {

        @XmlElement(name = "Reference", required = true)
        protected String reference;
        @XmlElement(name = "Amount")
        protected float amount;
        @XmlElement(name = "Currency", required = true)
        protected String currency;
        @XmlElement(name = "Email", required = true)
        protected String email;
        @XmlElement(name = "IPAddress", required = true)
        protected String ipAddress;
        @XmlElement(name = "Phone", required = true)
        protected String phone;
        @XmlElement(name = "FirstName", required = true)
        protected String firstName;
        @XmlElement(name = "LastName", required = true)
        protected String lastName;
        @XmlElement(name = "DOB")
        protected int dob;
        @XmlElement(name = "SSN")
        protected short ssn;
        @XmlElement(name = "Address", required = true)
        protected String address;
        @XmlElement(name = "City", required = true)
        protected String city;
        @XmlElement(name = "State", required = true)
        protected String state;
        @XmlElement(name = "PostCode")
        protected short postCode;
        @XmlElement(name = "Country", required = true)
        protected String country;
        @XmlElement(name = "CardNumber")
        protected long cardNumber;
        @XmlElement(name = "CardExpMonth")
        protected byte cardExpMonth;
        @XmlElement(name = "CardExpYear")
        protected short cardExpYear;
        @XmlElement(name = "CardCVV")
        protected byte cardCVV;
        @XmlElement(name = "ShipTo", required = true)
        protected Request.Transaction.ShipTo shipTo;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String field1;

        /**
         * Gets the value of the reference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReference() {
            return reference;
        }

        /**
         * Sets the value of the reference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReference(String value) {
            this.reference = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         */
        public float getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         */
        public void setAmount(float value) {
            this.amount = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the ipAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIPAddress() {
            return ipAddress;
        }

        /**
         * Sets the value of the ipAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIPAddress(String value) {
            this.ipAddress = value;
        }

        /**
         * Gets the value of the phone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhone() {
            return phone;
        }

        /**
         * Sets the value of the phone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhone(String value) {
            this.phone = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the dob property.
         * 
         */
        public int getDOB() {
            return dob;
        }

        /**
         * Sets the value of the dob property.
         * 
         */
        public void setDOB(int value) {
            this.dob = value;
        }

        /**
         * Gets the value of the ssn property.
         * 
         */
        public short getSSN() {
            return ssn;
        }

        /**
         * Sets the value of the ssn property.
         * 
         */
        public void setSSN(short value) {
            this.ssn = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddress(String value) {
            this.address = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the postCode property.
         * 
         */
        public short getPostCode() {
            return postCode;
        }

        /**
         * Sets the value of the postCode property.
         * 
         */
        public void setPostCode(short value) {
            this.postCode = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the cardNumber property.
         * 
         */
        public long getCardNumber() {
            return cardNumber;
        }

        /**
         * Sets the value of the cardNumber property.
         * 
         */
        public void setCardNumber(long value) {
            this.cardNumber = value;
        }

        /**
         * Gets the value of the cardExpMonth property.
         * 
         */
        public byte getCardExpMonth() {
            return cardExpMonth;
        }

        /**
         * Sets the value of the cardExpMonth property.
         * 
         */
        public void setCardExpMonth(byte value) {
            this.cardExpMonth = value;
        }

        /**
         * Gets the value of the cardExpYear property.
         * 
         */
        public short getCardExpYear() {
            return cardExpYear;
        }

        /**
         * Sets the value of the cardExpYear property.
         * 
         */
        public void setCardExpYear(short value) {
            this.cardExpYear = value;
        }

        /**
         * Gets the value of the cardCVV property.
         * 
         */
        public byte getCardCVV() {
            return cardCVV;
        }

        /**
         * Sets the value of the cardCVV property.
         * 
         */
        public void setCardCVV(byte value) {
            this.cardCVV = value;
        }

        /**
         * Gets the value of the shipTo property.
         * 
         * @return
         *     possible object is
         *     {@link Request.Transaction.ShipTo }
         *     
         */
        public Request.Transaction.ShipTo getShipTo() {
            return shipTo;
        }

        /**
         * Sets the value of the shipTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.Transaction.ShipTo }
         *     
         */
        public void setShipTo(Request.Transaction.ShipTo value) {
            this.shipTo = value;
        }

        /**
         * Gets the value of the field1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getField1() {
            return field1;
        }

        /**
         * Sets the value of the field1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setField1(String value) {
            this.field1 = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="PostCode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
         *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "firstName",
            "lastName",
            "address",
            "city",
            "state",
            "postCode",
            "country"
        })
        public static class ShipTo {

            @XmlElement(name = "FirstName", required = true)
            protected String firstName;
            @XmlElement(name = "LastName", required = true)
            protected String lastName;
            @XmlElement(name = "Address", required = true)
            protected String address;
            @XmlElement(name = "City", required = true)
            protected String city;
            @XmlElement(name = "State", required = true)
            protected String state;
            @XmlElement(name = "PostCode")
            protected short postCode;
            @XmlElement(name = "Country", required = true)
            protected String country;

            /**
             * Gets the value of the firstName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFirstName() {
                return firstName;
            }

            /**
             * Sets the value of the firstName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFirstName(String value) {
                this.firstName = value;
            }

            /**
             * Gets the value of the lastName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLastName() {
                return lastName;
            }

            /**
             * Sets the value of the lastName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLastName(String value) {
                this.lastName = value;
            }

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddress(String value) {
                this.address = value;
            }

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCity() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCity(String value) {
                this.city = value;
            }

            /**
             * Gets the value of the state property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getState() {
                return state;
            }

            /**
             * Sets the value of the state property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setState(String value) {
                this.state = value;
            }

            /**
             * Gets the value of the postCode property.
             * 
             */
            public short getPostCode() {
                return postCode;
            }

            /**
             * Sets the value of the postCode property.
             * 
             */
            public void setPostCode(short value) {
                this.postCode = value;
            }

            /**
             * Gets the value of the country property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountry() {
                return country;
            }

            /**
             * Sets the value of the country property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountry(String value) {
                this.country = value;
            }

        }

    }

}
